now bionic libc_static can work, but I believe still many work need improvment
- updated kernel uapi headers
  following bionic/libc/kernel/README.TXT
  kernel version: linux-stable(https://github.com/gregkh/linux.git), branch v5.4.61
  notice due to python issue on ubuntu 20.04 LTS, I have to run the python command in
  Ubuntu 18.04.4 LTS, kernel: Linux td155 4.15.0-118-generic (which is another
  building server td155)
  notice after run script will update the uapi headers for other arches besides riscv64,
  but we don't test others, we only take care of riscv64

- implemented syscall ASM part
  update bionic/libc/tools/gensyscalls.py to generate syscall entries for riscv64
  remove syscall renameat() due to it is not supported on riscv64
  added fstatat64 && fstat64 for riscv64
  added renameat2 syscall for riscv64
  notice following syscalls are added but just fake to pass build, TBD
  - libc/arch-riscv64/bionic/__bionic_clone.S
  - libc/arch-riscv64/bionic/__set_tls.S
  - libc/arch-riscv64/bionic/_exit_with_stack_teardown.S
  - libc/arch-riscv64/bionic/syscall.S
  - libc/arch-riscv64/bionic/vfork.S
  - libc/arch-riscv64/bionic/setjmp.S

- fixed some compiling errors:
  - after upgrade the linux header files to v5.4.61, compiling report error
    that MAP_SHARED/MAP_PRIVATE cant be found.
    rootcause is after kernel v5.1, such constants macro are moved from
    asm-generic/mman-common.h to include/uapi/linux/mman.h
    commitid is:746c9398f5ac2b3f5730da4ed09e99ef4bb50b4a
    solution: added `#include <linux/mman.h>` together with
    `#include <sys/mman.h>`
  - "ISO C++ requires field designators to be specified in declaration order"
    for example:
    ```
    bionic/libc/bionic/abort.cpp:49:52: error: ISO C++ requires field designators
    to be specified in declaration order; field '' will be initialized after
    field 'sa_flags' [-Werror,-Wreorder-init-list]
    struct sigaction64 sa = { .sa_handler = SIG_DFL, .sa_flags = SA_RESTART };
                                                     ^~~~~~~~~~~~~~~~~~~~~~
    bionic/libc/bionic/abort.cpp:49:29: note: previous initialization for field '' is here
    struct sigaction64 sa = { .sa_handler = SIG_DFL, .sa_flags = SA_RESTART };
    ```
    not sure why original code can not pass compile with andorid clang
    solution: use dynamically initializion instead of static initialzation table
  - "error: array designators are a C99 extension [-Werror,-Wc99-designator]"
    for example:
    ```
    error: array designators are a C99 extension [-Werror,-Wc99-designator]
     [XXXX] = "Operation not permitted",
     ^~~~~~~
    1 error generated.
    ```
    not sure why original code can not pass compile with andorid clang
    solution: don't use array designators and rewrite the code

- rename some source files due to current ugly make system, to be improved later

- other minor misc changes